# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Indivisible TN-3
email: indivisibleTN3@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  We are a coalition of Tennessee's District 3 Indivisible groups, part of a grassroots effort to oppose Donald Trump's damaging agenda.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.indivisibleTN3.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: IndivisibleTN3

permalink: /:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
